---
# Native package installation for Alpine Linux

- name: Install native packages (apk)
  become: true
  community.general.apk:
    name: "{{ native_packages }}"
    state: present
  when: native_packages | length > 0
