---
# Native package installation for Arch Linux

- name: Install native packages (pacman)
  become: true
  community.general.pacman:
    name: "{{ native_packages }}"
    state: present
  when: native_packages | length > 0
