[tools]
ansible = "latest"
bun = "latest"
flutter = "latest"
go = "latest"
java = "latest"
node = "latest"
npm = "latest"
"npm:typescript" = "latest"
pipx = "latest"
pnpm = "latest"
python = "latest"
ruby = "3.3.5"
rust = "nightly"
uv = "latest"
"npm:typescript-language-server" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@vue/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:ansible-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"

[env]
MISE_LOADED = 1

[settings]
lockfile = true
experimental = true
