[tools]
ansible = "latest"
bun = "latest"
cargo = "latest"
flutter = "latest"
go = "latest"
java = "latest"
node = "latest"
pipx = "latest"
pnpm = "latest"
python = "latest"
ruby = "3.3.5"
rust = "latest"
uv = "latest"

[env]
MISE_LOADED = 1

[settings]
lockfile = true
