
[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/ghostty"
hook = "mkdir -p ~/.config/ghostty/themes && cp -f %f ~/.config/ghostty/themes/tinted-theming"
supported-systems = ["base16", "base24"]

# [[items]]
# path = "https://github.com/tinted-theming/tinted-terminal"
# name = "tinted-terminal"
# themes-dir = "themes/alacritty"
# hook = "cp -f %f ~/.config/alacritty/colors.toml && touch ~/.config/alacritty/alacritty.toml"
# supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-shell"
name = "tinted-shell"
themes-dir = "scripts"
hook = ". %f"

[[items]]
path = "https://github.com/tinted-theming/base16-vim"
name = "base16-vim"
themes-dir = "colors"

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
hook = "tmux source-file ~/.tmux.conf 2>/dev/null"
themes-dir = "colors"

[[items]]
path = "https://github.com/scaryrawr/base16-opencode"
name = "tinted-opencode"
hook = "mkdir -p ~/.config/opencode/themes && cp -f %f ~/.config/opencode/themes/tinted.json"
themes-dir = "themes"

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "tinted-fzf"
hook = ". %f"
themes-dir = "sh"
