---
# Docker role - Install Docker

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
